# Generated by Django 4.2.3 on 2023-09-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0002_categorymaintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collecte.categorymaintenance'),
            preserve_default=False,
        ),
    ]
