# Generated by Django 4.2.3 on 2023-09-02 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0003_maintenance_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='category',
        ),
        migrations.AddField(
            model_name='settingsite',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collecte.categorymaintenance'),
            preserve_default=False,
        ),
    ]
