# Generated by Django 3.2.12 on 2023-05-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0004_parameterswaterquality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectonsite',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
