# Generated by Django 3.2.12 on 2023-05-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collecte', '0006_auto_20230506_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterswaterquality',
            old_name='active',
            new_name='is_active',
        ),
    ]
