# Generated by Django 3.2.12 on 2023-06-22 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='departement',
        ),
        migrations.AddField(
            model_name='agence',
            name='departement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agence.departement'),
        ),
    ]
