# Generated by Django 3.2.12 on 2023-05-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0001_initial'),
        ('app', '0006_abonne_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='departement',
        ),
        migrations.AddField(
            model_name='agence',
            name='departement',
            field=models.ManyToManyField(blank=True, null=True, to='agence.Departement'),
        ),
    ]
